CREATE USER 'filemount'@'127.0.0.1' IDENTIFIED BY 'filemount';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW ON *.* TO 'filemount'@'127.0.0.1';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `filemount`.* TO 'filemount'@'127.0.0.1';

GRANT GRANT OPTION ON `filemount`.* TO 'filemount'@'127.0.0.1';

